server:
  id: 1
  name: 'Hub 1'

servers:
  primaryHub:
    id: 1
    name: 'Hub 1'
    address: play.kingdom-smp.nl:25565

  secondaryHub:
    id: 2
    name: 'Hub 2'
    address: play.kingdom-smp.nl:25566
